# Neutral language (corrected MS)


# 
1) Keyborad Layout
2) UI language
3) Data format
   dates, times, numbers, currency, and measurement formats


Ubuntu https://help.ubuntu.com/stable/ubuntu-help/prefs-language.html.en
KeyboardLayouts http://xahlee.info/kbd/Japan_keyboard_layouts.html


# Decimal input
period and comma should be both supported - only one sign
space separation for groups


# Numeral Systems 
https://en.wikipedia.org/wiki/Numeral_system

# HTML Inputs https://html.spec.whatwg.org/multipage/input.html#number-state-(type%3Dnumber)
Jira
https://www.smashingmagazine.com/2018/08/ux-html5-mobile-form-part-2/

# Date picker
Chrome https://developers.google.com/web/updates/2012/08/Quick-FAQs-on-input-type-date-in-Google-Chrome
datetime-local is not supported by browsers https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#Browser_compatibility

# Intl Ecma scripts is not fully supported
http://www.ecma-international.org/ecma-402/1.0/
https://norbertlindenberg.com/2012/12/ecmascript-internationalization-api/index.html
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

# CLDR and ICU
CLDR - Unicode Common Locale Data Repository http://cldr.unicode.org/
ICU - International Components for Unicode http://site.icu-project.org/

#I18n-checker
http://validator.w3.org/i18n-checker

Ubuntu Locale https://help.ubuntu.com/community/Locale

# navigator.language and navigator.languages https://stackoverflow.com/questions/673905/best-way-to-determine-users-locale-within-browser
Accept-Language https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4

# UTF-8 is the best
https://www.w3.org/International/questions/qa-forms-utf-8

# W3C problems
Lloyd Honomichl
https://www.w3.org/International/questions/qa-accept-lang-locales.en
https://www.w3.org/International/questions/qa-date-format#japanese-eg

https://html.spec.whatwg.org/#input-author-notes
https://html.spec.whatwg.org/#input-impl-notes

# W3C i18n check list https://w3c.github.io/i18n-drafts/techniques/shortchecklist.html

# Unicode essential concept https://www.w3.org/International/articles/definitions-characters/

# Nokia globalisation
# SAP globalisation


## JS check 
https://stackoverflow.com/questions/22700527/how-to-approach-string-length-constraints-when-localization-is-brought-into-the
https://stackoverflow.com/questions/10442323/how-to-support-internationalization-for-string-validation

Array.from('🏃2🔥7') //returns ["🏃", "2", "🔥", "7"] https://stackoverflow.com/questions/37432321/javascript-unicodes-length-astral-symbols

https://stackoverflow.com/questions/31533053/set-length-limits-to-specific-character-class-parts-in-unicode-regular-expressio